databases:
  - name: Djangox
    plan: free
    databaseName: djangox_ytab
    user: djangox_ytab_user
    
services:
  - type: web
    plan: free
    name: Djangox
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn resume_demo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: postgres://djangox_ytab_user:UNUfxfGeri4ZzG457mKZZt0O4YlD2kd5@dpg-cnerdiol6cac73cp8l7g-a/djangox_ytab
        fromDatabase:
          name: Djangox
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
