# Generated by Django 4.1.7 on 2024-01-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactprofile',
            name='is_active',
        ),
    ]
