# Generated by Django 4.1.7 on 2024-01-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_message_contactprofile_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactprofile',
            old_name='messages',
            new_name='message',
        ),
    ]
