# Generated by Django 4.1.7 on 2024-01-21 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_messages_contactprofile_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['timestamp'], 'verbose_name': 'Contact profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
    ]
