# Generated by Django 4.1.7 on 2024-01-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_contactprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tech',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
